//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probashest
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вход гостя.
    /// </summary>
    // *** Start programmer edit section *** (ВходГостя CustomAttributes)

    // *** End programmer edit section *** (ВходГостя CustomAttributes)
    [AutoAltered()]
    [Caption("Вход гостя")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВходГостяE", new string[] {
            "Гость as \'Гость\'",
            "Гость.ФИО as \'ФИО\'",
            "Карты as \'Карта\'",
            "Карты.КодКарты as \'Код карты\'"}, Hidden=new string[] {
            "Гость.ФИО",
            "Карты.КодКарты"})]
    [MasterViewDefineAttribute("ВходГостяE", "Гость", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ВходГостяE", "Карты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКарты")]
    public class ВходГостя : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Probashest.Карты fКарты;
        
        private IIS.Probashest.Гость fГость;
        
        private IIS.Probashest.ДокРегВхода fДокРегВхода;
        
        // *** Start programmer edit section *** (ВходГостя CustomMembers)

        // *** End programmer edit section *** (ВходГостя CustomMembers)

        
        /// <summary>
        /// Вход гостя.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.Гость CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.Гость CustomAttributes)
        [PropertyStorage(new string[] {
                "Гость"})]
        [NotNull()]
        public virtual IIS.Probashest.Гость Гость
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.Гость Get start)

                // *** End programmer edit section *** (ВходГостя.Гость Get start)
                IIS.Probashest.Гость result = this.fГость;
                // *** Start programmer edit section *** (ВходГостя.Гость Get end)

                // *** End programmer edit section *** (ВходГостя.Гость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.Гость Set start)

                // *** End programmer edit section *** (ВходГостя.Гость Set start)
                this.fГость = value;
                // *** Start programmer edit section *** (ВходГостя.Гость Set end)

                // *** End programmer edit section *** (ВходГостя.Гость Set end)
            }
        }
        
        /// <summary>
        /// Вход гостя.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.Карты CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.Карты CustomAttributes)
        [PropertyStorage(new string[] {
                "Карты"})]
        [NotNull()]
        public virtual IIS.Probashest.Карты Карты
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.Карты Get start)

                // *** End programmer edit section *** (ВходГостя.Карты Get start)
                IIS.Probashest.Карты result = this.fКарты;
                // *** Start programmer edit section *** (ВходГостя.Карты Get end)

                // *** End programmer edit section *** (ВходГостя.Карты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.Карты Set start)

                // *** End programmer edit section *** (ВходГостя.Карты Set start)
                this.fКарты = value;
                // *** Start programmer edit section *** (ВходГостя.Карты Set end)

                // *** End programmer edit section *** (ВходГостя.Карты Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Probashest.ДокРегВхода.
        /// </summary>
        // *** Start programmer edit section *** (ВходГостя.ДокРегВхода CustomAttributes)

        // *** End programmer edit section *** (ВходГостя.ДокРегВхода CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ДокРегВхода"})]
        public virtual IIS.Probashest.ДокРегВхода ДокРегВхода
        {
            get
            {
                // *** Start programmer edit section *** (ВходГостя.ДокРегВхода Get start)

                // *** End programmer edit section *** (ВходГостя.ДокРегВхода Get start)
                IIS.Probashest.ДокРегВхода result = this.fДокРегВхода;
                // *** Start programmer edit section *** (ВходГостя.ДокРегВхода Get end)

                // *** End programmer edit section *** (ВходГостя.ДокРегВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВходГостя.ДокРегВхода Set start)

                // *** End programmer edit section *** (ВходГостя.ДокРегВхода Set start)
                this.fДокРегВхода = value;
                // *** Start programmer edit section *** (ВходГостя.ДокРегВхода Set end)

                // *** End programmer edit section *** (ВходГостя.ДокРегВхода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВходГостяE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВходГостяE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВходГостяE", typeof(IIS.Probashest.ВходГостя));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ВходГостя.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfВходГостя CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfВходГостя CustomAttributes)
    public class DetailArrayOfВходГостя : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Probashest.DetailArrayOfВходГостя members)

        // *** End programmer edit section *** (IIS.Probashest.DetailArrayOfВходГостя members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ВходГостя by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ВходГостя.
        /// </summary>
        public DetailArrayOfВходГостя(IIS.Probashest.ДокРегВхода fДокРегВхода) : 
                base(typeof(ВходГостя), ((ICSSoft.STORMNET.DataObject)(fДокРегВхода)))
        {
        }
        
        public IIS.Probashest.ВходГостя this[int index]
        {
            get
            {
                return ((IIS.Probashest.ВходГостя)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Probashest.ВходГостя dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
