//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probashest
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Док рег входа.
    /// </summary>
    // *** Start programmer edit section *** (ДокРегВхода CustomAttributes)

    // *** End programmer edit section *** (ДокРегВхода CustomAttributes)
    [AutoAltered()]
    [Caption("Док рег входа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокРегВходаE", new string[] {
            "Дата as \'Дата\'",
            "Комнаты as \'Комната\'",
            "Комнаты.Номер as \'Номер\'"}, Hidden=new string[] {
            "Комнаты.Номер"})]
    [AssociatedDetailViewAttribute("ДокРегВходаE", "ВходГостя", "ВходГостяE", true, "", "Вход гостя", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("ДокРегВходаE", "ВходСотрудника", "ВходСотрудникаE", true, "", "Вход сотрудника", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ДокРегВходаE", "Комнаты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("ДокРегВходаL", new string[] {
            "Дата as \'Дата\'",
            "Комнаты.Номер as \'Номер\'"})]
    public class ДокРегВхода : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Probashest.Комнаты fКомнаты;
        
        private IIS.Probashest.DetailArrayOfВходГостя fВходГостя;
        
        private IIS.Probashest.DetailArrayOfВходСотрудника fВходСотрудника;
        
        // *** Start programmer edit section *** (ДокРегВхода CustomMembers)

        // *** End programmer edit section *** (ДокРегВхода CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДокРегВхода.Дата CustomAttributes)

        // *** End programmer edit section *** (ДокРегВхода.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДокРегВхода.Дата Get start)

                // *** End programmer edit section *** (ДокРегВхода.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДокРегВхода.Дата Get end)

                // *** End programmer edit section *** (ДокРегВхода.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокРегВхода.Дата Set start)

                // *** End programmer edit section *** (ДокРегВхода.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДокРегВхода.Дата Set end)

                // *** End programmer edit section *** (ДокРегВхода.Дата Set end)
            }
        }
        
        /// <summary>
        /// Док рег входа.
        /// </summary>
        // *** Start programmer edit section *** (ДокРегВхода.Комнаты CustomAttributes)

        // *** End programmer edit section *** (ДокРегВхода.Комнаты CustomAttributes)
        [PropertyStorage(new string[] {
                "Комнаты"})]
        [NotNull()]
        public virtual IIS.Probashest.Комнаты Комнаты
        {
            get
            {
                // *** Start programmer edit section *** (ДокРегВхода.Комнаты Get start)

                // *** End programmer edit section *** (ДокРегВхода.Комнаты Get start)
                IIS.Probashest.Комнаты result = this.fКомнаты;
                // *** Start programmer edit section *** (ДокРегВхода.Комнаты Get end)

                // *** End programmer edit section *** (ДокРегВхода.Комнаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокРегВхода.Комнаты Set start)

                // *** End programmer edit section *** (ДокРегВхода.Комнаты Set start)
                this.fКомнаты = value;
                // *** Start programmer edit section *** (ДокРегВхода.Комнаты Set end)

                // *** End programmer edit section *** (ДокРегВхода.Комнаты Set end)
            }
        }
        
        /// <summary>
        /// Док рег входа.
        /// </summary>
        // *** Start programmer edit section *** (ДокРегВхода.ВходГостя CustomAttributes)

        // *** End programmer edit section *** (ДокРегВхода.ВходГостя CustomAttributes)
        public virtual IIS.Probashest.DetailArrayOfВходГостя ВходГостя
        {
            get
            {
                // *** Start programmer edit section *** (ДокРегВхода.ВходГостя Get start)

                // *** End programmer edit section *** (ДокРегВхода.ВходГостя Get start)
                if ((this.fВходГостя == null))
                {
                    this.fВходГостя = new IIS.Probashest.DetailArrayOfВходГостя(this);
                }
                IIS.Probashest.DetailArrayOfВходГостя result = this.fВходГостя;
                // *** Start programmer edit section *** (ДокРегВхода.ВходГостя Get end)

                // *** End programmer edit section *** (ДокРегВхода.ВходГостя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокРегВхода.ВходГостя Set start)

                // *** End programmer edit section *** (ДокРегВхода.ВходГостя Set start)
                this.fВходГостя = value;
                // *** Start programmer edit section *** (ДокРегВхода.ВходГостя Set end)

                // *** End programmer edit section *** (ДокРегВхода.ВходГостя Set end)
            }
        }
        
        /// <summary>
        /// Док рег входа.
        /// </summary>
        // *** Start programmer edit section *** (ДокРегВхода.ВходСотрудника CustomAttributes)

        // *** End programmer edit section *** (ДокРегВхода.ВходСотрудника CustomAttributes)
        public virtual IIS.Probashest.DetailArrayOfВходСотрудника ВходСотрудника
        {
            get
            {
                // *** Start programmer edit section *** (ДокРегВхода.ВходСотрудника Get start)

                // *** End programmer edit section *** (ДокРегВхода.ВходСотрудника Get start)
                if ((this.fВходСотрудника == null))
                {
                    this.fВходСотрудника = new IIS.Probashest.DetailArrayOfВходСотрудника(this);
                }
                IIS.Probashest.DetailArrayOfВходСотрудника result = this.fВходСотрудника;
                // *** Start programmer edit section *** (ДокРегВхода.ВходСотрудника Get end)

                // *** End programmer edit section *** (ДокРегВхода.ВходСотрудника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокРегВхода.ВходСотрудника Set start)

                // *** End programmer edit section *** (ДокРегВхода.ВходСотрудника Set start)
                this.fВходСотрудника = value;
                // *** Start programmer edit section *** (ДокРегВхода.ВходСотрудника Set end)

                // *** End programmer edit section *** (ДокРегВхода.ВходСотрудника Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокРегВходаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокРегВходаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокРегВходаE", typeof(IIS.Probashest.ДокРегВхода));
                }
            }
            
            /// <summary>
            /// "ДокРегВходаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокРегВходаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокРегВходаL", typeof(IIS.Probashest.ДокРегВхода));
                }
            }
        }
    }
}
